### ISSUE TITLE
Undefined Variable _result

### ISSUE THREAD

**Issue by ReDBaroN1** [Bones50/ammoSave#2]
Hey, sorry it's me again... I've got a few server.rpt errors since installing so, have posted each as a separate comment below.
This one is for undefined variable _result in object vehicle database load. Don't worry about my file location, I run my server overrides direct in exile_server folder to keep as much server side as possible. error below:
`22:52:59 Error in expression <VehicleAmmo:%1", _vehicleID];
_data1 = (_result select 1) select 0;
_savedMagazi>
22:52:59   Error position: <_result select 1) select 0;
_savedMagazi>
22:52:59   Error Undefined variable in expression: _result
22:52:59 File exile_server\code\ExileServer_object_vehicle_database_load.sqf, line 30
`

**Comment by ReDBaroN1** [comment]
Here's another:
`23:09:55 Error in expression <vehicle_database_update.sqf"











private["_vehicleObject", "_vehicleID", >
23:09:55   Error position: <private["_vehicleObject", "_vehicleID", >
23:09:55   Error Local variable in global space
23:09:55 File exile_server\code\ExileServer_object_vehicle_database_update.sqf, line 12
`

**Comment by ReDBaroN1** [comment]
and another:
`23:10:18 Error in expression <ield = _fields select _i;
if ((typeName _field) isEqualTo "SCALAR") then 
{
_fie>
23:10:18   Error position: <_field) isEqualTo "SCALAR") then 
{
_fie>
23:10:18   Error Undefined variable in expression: _field
23:10:18 File exile_server\code\ExileServer_util_extDB2_createMessage.sqf, line 19
`

**Comment by ReDBaroN1** [comment]
another:
`23:10:18 Error in expression <uery_fireAndForget;	

_currentLoadout = _vehicle call Bones_fnc_getVehicleLoadou>
23:10:18   Error position: <_vehicle call Bones_fnc_getVehicleLoadou>
23:10:18   Error Undefined variable in expression: _vehicle
23:10:18 File exile_server\code\ExileServer_object_vehicle_database_update.sqf, line 54
`

**Comment by Se7eN-Exile** [comment]
Change init.sqf to
Bones_fnc_getVehicleLoadout = compileFinal preprocessFileLineNumbers "Custom\ammoSave\Bones_fnc_getVehicleLoadout.sqf";

**Comment by ReDBaroN1** [comment]
These are all fixed with the new files. Thanks! :)
