### ISSUE TITLE
Change Init.sqf

### ISSUE THREAD

**Issue by xdavirus** [Bones50/ammoSave#3]
Change Init.sqf to
Bones_fnc_getVehicleLoadout = compileFinal preprocessFileLineNumbers "Custom\ammoSave\Bones_fnc_getVehicleLoadout.sqf";
and all should work.

**Comment by ReDBaroN1** [comment]
I don't think the brackets made any difference, certainly not to me anyway. But, definitely the ';' at the end of the line is needed to not break the rest of the init.

**Comment by Bones50** [comment]
Done! Cheers.
