### ISSUE TITLE
One New server.rpt error since the file changes

### ISSUE THREAD

**Issue by ReDBaroN1** [Bones50/ammoSave#4]
I've closed my other issue with rpt errors as they've cleared up now since you swapped in the new files. Not sure what the guy on the exile mod forum post is doing to get the other errors he's posted but, from my most recent test I only have this one:
` 8:00:48 Error in expression <ject setVehicleAmmoDef 0;

if (typeName _savedMagazines isEqualTo "ARRAY") then
>
 8:00:48   Error position: <_savedMagazines isEqualTo "ARRAY") then
>
 8:00:48   Error Undefined variable in expression: _savedmagazines
 8:00:48 File exile_server\code\ExileServer_object_vehicle_database_load.sqf, line 112
`
I am also running extDB3 but, I'm not convinced this error is related as it states it's an undefined variable. 
Plus, apart from the error, in my tests so far this addon is now actually working as expected. However, I have a few more tests to run yet.

**Comment by Bones50** [comment]
Just testing a fix. Will update asap. Let me know if you find anything else.

**Comment by ReDBaroN1** [comment]
Perfect! All fixed, thanks very much. Everything working as expected. :)
